### ISSUE TITLE
Clarification on real time interaction

### ISSUE THREAD

**Issue by cheneyzhoucheng** [cheneyzhoucheng/network-digital-twin#8]

**Comment by billwuqin** [comment]
Already clarified in section 3.3, quote text as follows:
"
Note: Real-time interaction is not always mandatory for all twins. When testing some configuration changes or trying some innovative techniques, the digital twins can behave as a simulation platform without the need of real time telemetry data. And even in this scenario, it is better to have interactive mapping capability so that the validated changes can be tested in real network whenever required by the testers. In most other cases (e.g., network optimization, network fault recovery), real-time interaction between virtual and real network is mandatory. This way, network digital twin can help achieve the goal of autonomous network or self-driven network.
"
